export enum AppException {
  INTERNAL_SERVER = 'INTERNAL_SERVER',
  AUTHORIZATION = 'AUTHORIZATION',
  AUTHENTICATION = 'AUTHENTICATION',
  FORBIDDEN = 'FORBIDDEN',
  BAD_REQUEST = 'BAD_REQUEST',
  CONFLICT = 'CONFLICT',
  NOT_FOUND = 'NOT_FOUND',
  NOT_IMPLEMENTED = 'NOT_IMPLEMENTED',
  VALIDATION = 'VALIDATION',
  ENTITY_NAME_ERROR = 'ENTITY_NAME_ERROR',
  CANNOT_REMOVE = 'CANNOT_REMOVE',
}
